# Generated by Django 4.1.7 on 2023-04-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=22)),
                ('gender', models.CharField(blank=True, max_length=6)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(max_length=22)),
                ('signup_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
