# Generated by Django 4.1.7 on 2023-04-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afro_dtl', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='my_msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
