# Generated by Django 4.1.7 on 2023-04-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afro_dtl', '0003_alter_message_my_msg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='CustomMessage',
        ),
    ]
