# Generated by Django 4.1.7 on 2023-04-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afro_dtl', '0004_rename_message_custommessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messenger', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True, max_length=255)),
            ],
        ),
    ]
